version: '3.8'

services:
  tg_timecheck_db:
    container_name: tg_timecheck_db
    ports:
      - 5416:5432
    image: postgres:latest
    volumes:
      - my_data_volume:/var/lib/postgresql/data
    env_file:
      - .env
  telegram_bot:
    container_name: telegram_bot
    depends_on:
      - tg_timecheck_db
    build: .
    volumes:
      - my_data_volume:/app/data
    env_file:
      - .env

volumes:
  my_data_volume: